### ISSUE TITLE
Refund Issues

### ISSUE THREAD

**Issue by PeteMcD85** [PeteMcD85/FerreteriaReact#66]
1) Error when deleting Item_order thats been refunded, not converting to a custom item.

2) After doing a refund, show how many more items can be refunded in table.

3) Total refund not showing in orders refund table, in the Order Index page.

**Comment by stevemcd87** [comment]
This should be 3 different issues that can could be put in a [milestone](https://help.github.com/en/github/managing-your-work-on-github/about-milestones) if you think the should be group.

**Comment by stevemcd87** [comment]
1. Complete
2. Now showing the total refunded quantity
3. Complete(Updated both, Order table and RefundedOrders table)

Already merged into master.

Please close issue if satisfied with changes.

**Comment by PeteMcD85** [comment]
Good Job on the other 3.

- In Orders/id/refund_orders/new, for each item show how many items are left that can be refunded .
