### ISSUE TITLE
Saving Cart Issues

### ISSUE THREAD

**Issue by PeteMcD85** [PeteMcD85/FerreteriaReact#67]
1) After saving cart, Render items Index/ homepage

2) When you click on the saved cart, render the cart.

3) When click the X on the saved cart button, delete/clear cart

**Comment by stevemcd87** [comment]
1. Complete

2. Complete

3. Create separate issue labeled 'enhancement'
      Must make sure savedCart is selected before clearing cart

Please close issue when you test again

**Comment by PeteMcD85** [comment]
when you click on the X in the saved cart box, while in the cart... It should clear cart and render items index page
