### ISSUE TITLE
Duplicate Files

### ISSUE THREAD

**Issue by PeteMcD85** [PeteMcD85/FerreteriaReact#70]
1) Delete all duplicate files like Accountant 2.jsx,  Cart 2.jsx, ItemsCard 2.jsx, ItemsTable 2.jsx, etc.... Make sure they're all in the right folders etc.

**Comment by stevemcd87** [comment]
I don't see those files in master,they must be only in your computer.

Make sure to delete before pushing to master.

**Comment by PeteMcD85** [comment]
It was in both but i deleted them
